<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
        <PackageVersion Include="Microsoft.Maui.Controls" Version="9.0.110" />
        <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    </ItemGroup>

</Project>
